<?php
/**
 * TL_ROOT/system/modules/backend_password/languages/de/default.php 
 * 
 * Contao extension: backend_password 3.0.0 
 * Deutsch translation file 
 * 
 * Copyright : © Andreas Schempp und Marko Cupic 2015 
 * License   : LGPL 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Andreas Schempp (andreas.schempp), http://www.terminal42.ch/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['pwrecoveryFailed'] = "Kein Benutzer mit diesem Benutzernamen oder dieser E-Mail-Adresse gefunden.";
$GLOBALS['TL_LANG']['ERR']['invalidBackendLogin'] = "Anmeldung fehlgeschlagen! <a href=\"contao/index.php?pwrecovery=1\">Passwort vergessen?</a>";
$GLOBALS['TL_LANG']['ERR']['accountLocked'] = "Das Konto wurde gesperrt! Sie können sich in %d Minuten erneut anmelden. <a href=\"contao/index.php?pwrecovery=1\">Passwort vergessen?</a>";
$GLOBALS['TL_LANG']['MSC']['emailOrUsername'] = "Bitte geben Sie Ihre E-Mail-Adresse oder Ihren Benutzernamen ein.";
$GLOBALS['TL_LANG']['MSC']['newPassword'] = "Bitte geben Sie Ihr neues Passwort ein.";
$GLOBALS['TL_LANG']['MSC']['beLogin'] = "Contao Backend-Login";
$GLOBALS['TL_LANG']['MSC']['pwrecovery'] = "Passwort zurücksetzen";
$GLOBALS['TL_LANG']['MSC']['recoverBT'] = "Passwort zurücksetzen";
$GLOBALS['TL_LANG']['MSC']['pwrecoverySuccess'] = "Sie erhalten nun eine E-Mail mit Hinweisen um Ihr Passwort zu ändern.";
$GLOBALS['TL_LANG']['MSC']['pwrecoveryText']['0'] = "Ihre Passwort-Anforderung auf %s";
$GLOBALS['TL_LANG']['MSC']['pwrecoveryText']['1'] = "Sie haben ein neues Passwort für %s angefordert.\n\nBitte klicken Sie %s um das neue Passwort festzulegen. Wenn Sie diese E-Mail nicht angefordert haben, kontaktieren Sie bitte den Administrator der Webseite.";
 
?>
